### ISSUE TITLE
Layout using GoogleMap breaks since Compose 1.4.0

### ISSUE THREAD

**Issue by svenjacobs** [googlemaps/android-maps-compose#295]
I just noticed when updating from Compose BOM `2023.01.00` (Compose `1.3.3`) to `2023.03.00` (Compose `1.4.0`), a layout with a `GoogleMap` composable breaks.

I have this (simplified) layout:

```kotlin
Column {
  GoogleMap(
    modifier = Modifier.fillMaxWidth().weight(1f)
  ) {
    …
  }

  Box {
    // More contents
  }
}
```

so `GoogleMap` should only take the remaining space. This worked fine before but now the `GoogleMap` composable fills the whole screen and the contents of `Box` is not visible anymore.

I'm not sure if this is some incompatibility with Compose 1.4.0?

Using `maps-compose` version `2.11.3`.

**Comment by am3712** [comment]
same problem face me any sol ..?

**Comment by svenjacobs** [comment]
> same problem face me any sol ..?

@am3712 As a workaround you can wrap your `GoogleMap` composable in a `Box` layout.

**Comment by DSteve595** [comment]
This seems to apply even to a non-GoogleMap `AndroidView` in Compose 1.4.0. Investigating, though it's likely not a fault of this library.

**Comment by svenjacobs** [comment]
> This seems to apply even to a non-GoogleMap `AndroidView` in Compose 1.4.0. Investigating, though it's likely not a fault of this library.

Oh 😱 This might be some bigger issue then! Thanks for investigating!

**Comment by DSteve595** [comment]
Should be fixed in Compose 1.4.1, which was just released.

**Comment by svenjacobs** [comment]
> Should be fixed in Compose 1.4.1, which was just released.

I can confirm that it was fixed for `AndroidView` but I still have the problem with `GoogleMap`. Please see my [sample project](https://github.com/svenjacobs/maps-compose-issue-295). Does `maps-compose` need to be updated to BOM `2023.04.00`, too?

**Comment by DSteve595** [comment]
That's concerning. Will take a look.

> Does `maps-compose` need to be updated to BOM `2023.04.00`, too?

I wouldn't think so, as it should use the version in your project.

**Comment by svenjacobs** [comment]
Unfortunately still the same issue with Compose BOM `2023.04.01` (Compose UI `1.4.2`).

**Comment by mtangoo** [comment]
Just to confirm the problem still exists in compose `1.4.2` and map compose `2.11.2`

**Comment by svenjacobs** [comment]
It seems this was completely fixed in Compose `1.4.3`.

**Comment by mtangoo** [comment]
I will check it out. I thought 1.4.2 was the latest!

**Comment by mtangoo** [comment]
Trie 1.4.3 with this code and Map Takes full space

```
 Column(
    modifier = Modifier
        .fillMaxSize()
) {
    GoogleMap(
        modifier = Modifier
            .fillMaxWidth()
            .weight(1f),
            ...
    ) {
        Marker(...)
    }

    Card(
        modifier = Modifier
            .fillMaxWidth()
            .height(200.dp),
        elevation = 10.dp
    ) {

    }
}
```
Is it my code or the problem still exists?

**Comment by svenjacobs** [comment]
@mtangoo Are you absolutely sure you are using Compose `1.4.3` (BOM `2023.05.00`)? I updated my [sample project](https://github.com/svenjacobs/maps-compose-issue-295) and it's working now with Compose `1.4.3`.

**Comment by mtangoo** [comment]
@svenjacobs 
I did update it on gradle, sync and run. I will try to invalidate cache and try clean and rebuild and see.

**Comment by mtangoo** [comment]
@svenjacobs it didn't work. I tried `1.5.0-alpha03` and worked fine. I will stick with that ATM
